### ISSUE TITLE
Add Aspace Environment Variables into ansible

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/aspace_helpers#175]
Add the information to the vault: https://github.com/pulibrary/princeton_ansible/blob/main/group_vars/lib_jobs/vault.yml

Then add environment variables here:
https://github.com/pulibrary/princeton_ansible/blob/main/roles/lib_jobs/vars/main.yml#L4

Last utilize the environment variables in the authorization file (It can now be checked into github and removed from https://github.com/pulibrary/aspace_helpers/blob/main/config/deploy.rb#L24)

**Comment by sandbergja** [comment]
@regineheberlein and @regineheberlein: this ticket is completed, and can be closed, right?

**Comment by regineheberlein** [comment]
no, this is still pending!

**Comment by christinach** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DACS-Maintenance-5da0db919c4ddf0001b2eb92/issues/pulibrary/aspace_helpers/175?planning-poker) with Zenhub @kevinreiss @maxkadel @regineheberlein @rladdusaw

**Comment by carolyncole** [comment]
https://github.com/pulibrary/princeton_ansible/commit/e2d55066e5f31cfc43bcdf5fd863a10912309cd0

**Comment by christinach** [comment]
we need to review the vault. @regineheberlein will update with the env keys

**Comment by regineheberlein** [comment]
we need base_uri, username, and password:
```
@config = ArchivesSpace::Configuration.new({
    base_uri: ENV['ASPACE_URL'],
    base_repo: "",
    username: ENV['ASPACE_USER'],
    password: ENV['ASPACE_PASSWORD'],
    #page_size: 50,
    throttle: 0,
    verify_ssl: false
  })
```

**Comment by regineheberlein** [comment]
credentials in LastPass in the Shared-ITIMS-Passwords directory (aspace2alma credentials)

**Comment by sandbergja** [comment]
@regineheberlein a few questions:

- does the ASPACE_URL need to be vaulted?
- I noticed that there are both `ASPACE_URL` and `ASPACE_STAGING_URL` environment variables in aspace_helpers.  Should both be set on each box?
- On a related note, I've used that test.rb script in the past as a quick check to make sure that authentication is working correctly -- but it's set to use `aspace_staging_login`.  Could we change it to `aspace_login` so it could test authenticating against either environment?  Or is there a better way to check authentication?

**Comment by regineheberlein** [comment]
Thanks @sandbergja ! You're right, the aspace url probably doesn't need to be vaulted.

I think we should set both urls on staging, but only ASPACE_URL on production, do you think that makes sense?

I haven't thought of the test.rb script as static. I use it to try things out all the time, and have assumed that others change it around as they need as well. Does that answer the question? Should we have a test_connection.rb?
