### ISSUE TITLE
change box label

### ISSUE THREAD

**Issue by regineheberlein** [pulibrary/aspace_helpers#217]
[Faith](https://app.slack.com/team/U946656J0)  [15 minutes ago](https://pulibrary.slack.com/archives/GCCLQS5U2/p1654887542571109?thread_ts=1654884346.267299&cid=GCCLQS5U2)
Hi [@Regine](https://pulibrary.slack.com/team/UA96YEM5M) - it may be difficult to interpret this thread, haha, but when you have a chance, might you be able to design a mockup of a box label in which the call number and box number display on different lines and in a larger font? The Collection Services team has asked if we can update box labels for easier paging. Thanks! (edited)

**Comment by regineheberlein** [comment]
[Alexis A. (she/her)](https://app.slack.com/team/U8DJD48SZ)  [< 1 minute ago](https://pulibrary.slack.com/archives/GCCLQS5U2/p1654888602000879?thread_ts=1654884346.267299&cid=GCCLQS5U2)
I think the CST and PS wants the box number to be more prominent than it is now, that's the main issue.

**Comment by regineheberlein** [comment]
This is for 3 1/3" x 4" labels

**Comment by regineheberlein** [comment]
https://github.com/pulibrary/aspace_helpers/blob/main/tools/aspace_BoxLabels

**Comment by regineheberlein** [comment]
[test.pdf](https://github.com/pulibrary/aspace_helpers/files/8881942/test.pdf)

**Comment by amycvo** [comment]
[Box Label Template Edit.pdf](https://github.com/pulibrary/aspace_helpers/files/8881960/Box.Label.Template.Edit.pdf)

**Comment by amycvo** [comment]
@regineheberlein we're ready! I think the only suggestion is that the box number font needs to be bigger. thank you for your help with this!

**Comment by regineheberlein** [comment]
Thanks!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by regineheberlein** [comment]
How about this?
[test.pdf](https://github.com/pulibrary/aspace_helpers/files/8891511/test.pdf)

**Comment by faithc** [comment]
This looks good to me. If any agrees, I can share it with adapt for confirmation. Thanks, Regine.

**Comment by amycvo** [comment]
I like it! Thanks, Regine!

**Comment by faithc** [comment]
Ok, so after consulting with folks again, the consensus is that the call number font should be a bit larger. Other than that, the label looks good. Thanks again for you help with this. :)

**Comment by faithc** [comment]
Haha, thanks, Regine. Looks good! Let's do it! :)

**Comment by regineheberlein** [comment]
Approved and ready to merge
