### ISSUE TITLE
AC107: create a potential-problems report

### ISSUE THREAD

**Issue by regineheberlein** [pulibrary/aspace_helpers#22]
What would/could be a problem after we do #21?

duplicate box numbers
blank indicators
wrong number got deleted (box # instead of year)

**Comment by regineheberlein** [comment]
Duplicates:

590
590
600
600
608
608
609
609
612
612
613
613
620
620
621
621
623
623
624
624
631
631
662
662
681
681
684
684
724
724
724
748
748
749
749
749
750
750
751
751
776
776
784
784
791
791
794
794
801
801
801
802
802
809
809
810
810
811
811
812
812
814
814
814
814
814
818
818
821
821
827
827
827
828
828
832
832
834
834
838
838
910
910
943
943
946
946
994
994
1016
1016
1018
1018
1021
1021
1038
1038
1040
1040

**Comment by regineheberlein** [comment]
One blank from "Primary"

**Comment by regineheberlein** [comment]
These break the pattern, is that ok? Should letters be taken out here, as well? (If so, 1, 2, and 14 would be additional duplicates.)

FAC14
FAC42
FACLP1
FACLP2

**Comment by Will-Clements** [comment]
> These break the pattern, is that ok? Should letters be taken out here, as well? (If so, 1, 2, and 14 would be additional duplicates.)
> 
> FAC14
> FAC42
> FACLP1
> FACLP2

These we want to leave alone.
