### ISSUE TITLE
folder label transformation prints "multiple items"

### ISSUE THREAD

**Issue by regineheberlein** [pulibrary/aspace_helpers#249]
from @faithc in https://github.com/pulibrary/aspace_helpers/issues/239

Re: folder labels, in cases where a component/archival object has an oversize folder or DO instance in addition to a box instance, folder labels say "Multiple Items" and display the title twice in small font. See for example the folder labels that generate for C0511_c0000030 (box + oversize folder) on the staging site and C0187_c03265 (box + DO) on the production site.

**Comment by regineheberlein** [comment]
@faithc is this the box label transformation? or the folder label transformation?

**Comment by faithc** [comment]
folder label

**Comment by regineheberlein** [comment]
thanks!

**Comment by regineheberlein** [comment]
@faithc 
The script is behaving as expected for C0187. It has nothing to do with the digital objects, but rather with the fact that there are three components with material (items) in Box 49, Folder 41. 

The script assumes that you'd want only one label for the one folder with three items in it, and de-dupes on the box/folder number while stringing together the titles of the three items, in this case "Wharton, Edith", "Wharton, Edith – Name Card with Address", and "Wharton, Edith".

We should probably change the punctuation here to make that scenario a little clearer to the eye. Let me know.

**Comment by faithc** [comment]
@amycvo FYI see above

**Comment by amycvo** [comment]
That instance is strange/unusual because a few items were already digitized and in Figgy, and linked to the finding aid. I may have manually labeled that folder, to get around the issue? I don't think it's an important scenario to consider for the script.

**Comment by regineheberlein** [comment]
I don't think it's anything you did! I think it's because of the item-level description. There are three components all referencing the same folder. In those situations, the script assumes 1) you want one folder label and 2) you still want to know all the component unittitles stored in that folder and 3) you want to know that this is one folder housing multiple components' worth of material. So it prints "Multiple Items" followed by the unittitles.
