### ISSUE TITLE
Add post-processing to 6xx's in aspace2alma collection-level process

### ISSUE THREAD

**Issue by phoebeno** [pulibrary/aspace_helpers#254]
See sehamerman's updated version below. Thanks Sarah.

**Comment by regineheberlein** [comment]
Thanks Phoebe. I'll take a look and see what we can do via post-processing the data.

**Comment by faithc** [comment]
Please implement this for both collection and component-level MARC records, i.e. records currently generated from C0140.

**Comment by regineheberlein** [comment]
superseded by the forthcoming proposal to DSSG to add 6xx ind2=7 with $2 to the index
