### ISSUE TITLE
fix spreadsheet for AC107.xx

### ISSUE THREAD

**Issue by regineheberlein** [pulibrary/aspace_helpers#261]
as discussed with Phoebe
--export AC107.xx EAD files
--get uri, cid from EAD files
--match on cid in spreadsheet to update misaligned uri column
--add column for name conditionally filled from old and new columns

**Comment by regineheberlein** [comment]
@phoebeno 
See if the added columns does what you need?

**Comment by phoebeno** [comment]
If you mean does the new_uri column contain the correct uris, yes, I believe so when I spot-check!
