### ISSUE TITLE
aspace2alma cron job should log errors and output on lib-jobs-prod1

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/aspace_helpers#269]
**Describe the bug**

When aspace2alma encounters an error while running on the lib-jobs server, the error is not logged.

**Steps to replicate**

@maxkadel, @regineheberlein, and I encountered the issue using the following steps:

1. SSH into lib-jobs-prod1
2. Run `crontab -a`
3. Notice that many jobs are logging to /opt/lib-jobs/shared/tmp/cron_log.log, and look in that file for any error messages
4. Note that there are no error messages from aspace2alma, despite the cron process having errored out the night before.
5. Note that the crontab entry for aspace2alma doesn't write its output to any file, so there is no log to check

**Expected behavior**

The crontab entry sends STDERR and STDOUT to a log.

### Impact of this bug

Difficult to investigate issues with aspace2alma.

**Contact**

@regineheberlein, @maxkadel, @sandbergja

**Comment by regineheberlein** [comment]
#330 is now logging from inside Ruby
