### ISSUE TITLE
Update/generate C0140, AC214, AC364 component-level MARC records daily

### ISSUE THREAD

**Issue by faithc** [pulibrary/aspace_helpers#271]
In the same way that collection-level MARC records are updated or generated from Resource records, C0140 MARC records should be updated or generated from archival objects on a daily basis.

**Comment by regineheberlein** [comment]
link to a proposal from Slack: https://docs.google.com/document/d/1LiqIMnUQoXjoSkOaaLRjIcSOq6aC9YHxdG2gnz0xzcM/edit#

**Comment by regineheberlein** [comment]
@faithc We're going to talk to HM about developing this as a plugin. I'll post updates here.

**Comment by faithc** [comment]
Ok. Thanks, Regine.

**Comment by regineheberlein** [comment]
Update: we're expecting to receive a quote sometime soon.

**Comment by regineheberlein** [comment]
Update: HM has started working on this

**Comment by regineheberlein** [comment]
The plugin is ready for testing. Closing this ticket in the expectation that we'll use the plugin from now on.
