### ISSUE TITLE
AC107.01-AC107.16 change names of container indicators that have prefixes

### ISSUE THREAD

**Issue by phoebeno** [pulibrary/aspace_helpers#276]
This ticket requests to remove prefixes from existing container indicators in AC107 (which spans finding aids AC107.01 to AC107.16). Indicators have prefixes such as the words "Primary," "Consolidated Run," "Annual," as well as numerical (date) prefixes "1996" to "2014." We would like to strip these, leaving simple box numbers (see implementation notes below for complication). All of these containers are linked to multiple files in multiple finding aids. 

We also would like to have the box type changed. It is currently "NBox" in most cases. Boxes 1-607 should be changed to standard manuscript boxes. Boxes 608-1067 should be changed to standard record center cartons. There is a "container profile" column in the spreadsheet that reflects this.

I believe that the locations on these containers are already correct in ASpace. There are two locations. Boxes 1-839 are all at Mudd, and Boxes 840-1067 are at ReCAP. I did leave a "location" column in the spreadsheet in case it is necessary. 

### Source of the data to be imported or updated
I am sending you an excel sheet, "AC107_Change_Container_Indicators"

### Implementation notes, if any:

The indicator change is, unfortunately, not a simple 1:1 change. There are multiple containers in many of these cases that need to be merged into one. Examples below.

Some containers have multiple different prefixes; a few already exist with no prefix but are duplicated by a container instance that does have a prefix. 

For instance, there are presently two containers that should equal one Box 749. There is Box "749" and there is Box "n.a. 749." Box 749 currently exists with no prefix, but Box "n.a. 749" should be merged into Box 749. Box 724 has three forms, one of them without a prefix, two others with different prefixes.

Sometimes there are two containers because the prefix is used as a prefix once and a suffix once. So for instance, there is Box "2003 776" and Box "776 2003." These should both just be "776."

There are also sometimes containers prefixed "file not extant." So, both Box "file not extant 590" and Box "Consolidated Run 590" should become one box, 590.

Also, a box such as 814 has five different prefixed containers that should all be the same container. They are 2004 814, 2001 814, 2000 814, 2005 814, and 2002 814. These should all just become part of one plain "814" box.

**Comment by regineheberlein** [comment]
@phoebeno 
Thanks for explaining the situation! I suggest we make a separate ticket (and a separate input data spreadsheet) for the merging of containers. 

For the step of renaming the containers, it would be helpful if you could give me a spreadsheet with a single tab and the following fields:

instance_uri
old_instance_type
new_instance_type
old_instance_indicator
new_instance_indicator
old_location_uri
new_location_uri

You should be able to attach the Excel sheet here directly.

**Comment by regineheberlein** [comment]
Investigate whether containers are linked to locations or vv; we may need a separate step for that

**Comment by phoebeno** [comment]
@regineheberlein OK, working! can I make one change? since the old and new "type" are both just "box," I am substituting columns that say old_instance_profile (N-box) and new_instance_profile (such as standard ms box). There is no change to make in "type."

**Comment by phoebeno** [comment]
I am fairly certain that almost all these containers will still have the old_instance_profile "NBox" (container_profiles/3). But I do not have a good way to pull the data for the old profile or the old location uri, so those columns are blank. I entered the data for Box Primary 1, where old profile is NBox and old location is "review."

**Comment by regineheberlein** [comment]
@phoebeno 
Sorry this took a while. FYI the uri's should start with `/`. ;-)

The records are now in staging. Take a look and let me know if they can be run in production?

**Comment by phoebeno** [comment]
Thank you, Regine!! The box numbers look lovely and unprefixed, but I am noticing that there are some duplicate boxes. For example, there are 2 of Box 590, 609, 612, and quite a few others, 3 of Box 724. I can see that it happened because there used to be both a "File not extant 590" and a "Consolidated Run 590." When we make them a new "Box 590," is there a way to make it be the same Box 590?

**Comment by regineheberlein** [comment]
Yes! As previously discussed, could you make a separate ticket for the merge, and could you provide the input data for the containers you want to be merged? I need the "target" uri (the target that will receive the merge) and the "victim" uri (the uri that will be merged into the other uri).

We can then run the two processes in succession on prod.

**Comment by phoebeno** [comment]
Ah, sorry I forgot what was previously discussed and is also written above. Brain was so far from AC107 for a while. Ticket, etc. forthcoming.

**Comment by phoebeno** [comment]
Please forgive long hiatus. Created other ticket 318 for merging containers. Please let me know if it looks at all like what you might need.

**Comment by regineheberlein** [comment]
See #318
