### ISSUE TITLE
interim workflow for C0140

### ISSUE THREAD

**Issue by regineheberlein** [pulibrary/aspace_helpers#3]
Each item in this collection needs its own Voyager record. This means each component in the EAD needs to be transformed to MARC.

**Comment by regineheberlein** [comment]
@faithc Can you tell me more? Is this a retrospective project, or an ongoing workflow we need to develop? Or both?

**Comment by faithc** [comment]
It's both. Per recommendations approved by DSSG for managing single-item acquisitions, we had requested that individual MARC records be created for all components in C0140 to allow for increased discoverability of materials that represent standalone items. (We'll now be adding most single-item acquisitions to this collection rather than arbitrarily adding them to various format, subject, or topic-based collections as had been done previously.)

**Comment by regineheberlein** [comment]
A couple of questions.
There is a collection-level record for this in Voyager, do you want to keep it?
There are also two items already cataloged, are we replacing those?
How urgent is this? Between the retroactive part and the prospective workflow, which has higher priority?

**Comment by faithc** [comment]
1. It looks like there are two collection-level records: Bib ID 6429525 and 4545710? No idea what the deal is with the second record, haha, but they can both be deleted. 
2. Please keep the suppressed record Bib ID 4541023; no idea what's going on here either. You can delete 9187631.
3. This isn't urgent; I would say the prospective workflow is the higher priority.
Thanks.

**Comment by regineheberlein** [comment]
I'd rather that you delete what you don't need, if possible.

Ok, I'll look into it. How do you imagine the prospective workflow? What should happen on the processing archivist's end?

**Comment by faithc** [comment]
I don't have permission to delete records. 

And sorry, not quite sure what you're asking re: workflow. Would processors need to do anything beyond creating the archival objects?

**Comment by regineheberlein** [comment]
Ok, I'll delete 6429525, 4545710, and 9187631.

I'm afraid that a fully automated workflow will need to wait until the Alma migration is done. Hence the question of what you envision for an interim one that could work. Though for the development time that will have to go into even that, I'm wondering whether it wouldn't be more straightforward if the archivists just created the Voyager records at the same time as the EAD records.

**Comment by faithc** [comment]
Thanks.

And ah, gotcha. It might be better to just wait until the Alma migration is done then. Again, we're not in any particular rush, and trying to come up with something in the meantime, especially if it involves manual work, is probably more effort than it's worth. When is the migration supposed to be completed?

**Comment by faithc** [comment]
And maybe we should leave the legit collection-level record up until then.

**Comment by regineheberlein** [comment]
Oh no. I already deleted them. It's all gone except 4545710.

**Comment by faithc** [comment]
Haha whoops. Well, that collection-level record isn't really useful. Lemme check in with folks, but as I said, thinking we can just wait until the Alma migration is completed. What is the projected date for that?

**Comment by regineheberlein** [comment]
I unsuppressed 4545710 for now...

The Alma migration is slated to be finished by the end of July.

**Comment by faithc** [comment]
Ok, yeah, we're good with waiting until summer for this to happen. Don't want to be creating records in two places. :) Thanks for checking in about it.

**Comment by regineheberlein** [comment]
Ok, thanks!
