### ISSUE TITLE
Add barcodes to TC099

### ISSUE THREAD

**Issue by faithc** [pulibrary/aspace_helpers#317]
### User story

Warner Bros. Screenplays, TC099, which is stored at ReCAP, does not have barcodes associated with any top container records in ASpace. The resource is part of the Rare Books repo. There are barcodes for containers in item records in Alma. This issue was discovered when public svs staff reached out that an error occurred when a request from the finding aid site was made. Could the barcodes be imported into ASpace from Alma? Thanks!

### Source of the data to be imported or updated
A link to a spreadsheet or similar containing the URI's you need edited and the fields you want imported or changed. Please don't submit "living" spreadsheets for this purpose and and limit the columns in the spreadsheet to data needed for the import.

### Implementation notes, if any
Describe any factors that might affect the data update, e.g. does existing data need to be checked first? Does the successful import depend on other operations, e.g. deletions or other steps that need to be completed first?

**Comment by regineheberlein** [comment]
@faithc 
Can you please attach a spreadsheet here containing the barcode and the the top_container uri? 

(In case you didn't know, you can easily export the item records from Alma by going to the collection record > Items > export.) 

Thanks!

**Comment by faithc** [comment]
Ohhh, I did NOT know that. Thanks! Spreadsheet attached. 
[TC099_barcodes.xlsx](https://github.com/pulibrary/aspace_helpers/files/10355497/TC099_barcodes.xlsx)

**Comment by regineheberlein** [comment]
@faithc Which repo are these top_containers in?

**Comment by faithc** [comment]
rare books

**Comment by regineheberlein** [comment]
Ok, thanks! Typically, the uri should look like this (and contain the repo number): 

`repositories/6/top_containers/47145`

For top_container records, the uri is at the bottom of the record. I'll update the input data you provided.

**Comment by faithc** [comment]
Ahhh ok re: the location of the URI. I had just used the record's URLs, as you can see. Whoops. Thanks for updating the data!

It might be helpful to note where staff can locate URIs for different record types in the template you created unless that info is somewhere else that I'm not aware of?

**Comment by regineheberlein** [comment]
@faithc Can you QA on staging please?

**Comment by faithc** [comment]
Looks good to me. Thanks, Regine.
