### ISSUE TITLE
AC107 merge duplicate containers

### ISSUE THREAD

**Issue by phoebeno** [pulibrary/aspace_helpers#318]
### Source of the data to be imported or updated: [](url)
[AC107_Merge_Duplicate_Containers.xlsx](https://github.com/pulibrary/aspace_helpers/files/10355500/AC107_Merge_Duplicate_Containers.xlsx)

**Comment by regineheberlein** [comment]
@phoebeno 
Thanks for providing this. Quick question--what is the significance of the containers highlighted in yellow?

**Comment by phoebeno** [comment]
Sorry @regineheberlein , I believe that is old highlighting that you are free to ignore.

**Comment by regineheberlein** [comment]
Ok, thanks!

**Comment by regineheberlein** [comment]
@phoebeno 
Can you QA the merge on staging please?

**Comment by phoebeno** [comment]
@regineheberlein OK, they look good to me! thanks

**Comment by regineheberlein** [comment]
@phoebeno 
Thanks for QA'ing! Do you want me to run #276 and #318 (this ticket) in production?

**Comment by phoebeno** [comment]
@regineheberlein yes please . . . unless you want to wait for the next ticket--for adding containers that do not exist yet (to many components)

**Comment by regineheberlein** [comment]
#320 has no technical impact on running #276 and #318, so whenever you prefer!

**Comment by phoebeno** [comment]
I think it would be great to run them now and at least clear up the existing containers
