### ISSUE TITLE
AC107.01-AC107.16 create new container records

### ISSUE THREAD

**Issue by phoebeno** [pulibrary/aspace_helpers#320]
### Source of the data to be imported or updated
[AC107_Add_New_Containers.xlsx](https://github.com/pulibrary/aspace_helpers/files/10355584/AC107_Add_New_Containers.xlsx)

**Comment by regineheberlein** [comment]
@phoebeno 
Are these containers that you have created in ASpace and need me to link, or are they containers that you want me to create in ASpace and then link?

**Comment by phoebeno** [comment]
I have not created them--I have never created a lot of containers in bulk--can I do it in the user interface?

**Comment by regineheberlein** [comment]
No worries, I can create them for you--I just wanted to be sure I understand and not create duplicates! If I need additional information for the required fields I'll let you know.

**Comment by phoebeno** [comment]
Thank you! You can see that between Box 24 and Box 588, there are a few that have been created already: 55, 61, 66, 67, 364, and 517-525. Oh, and I have profiles. All boxes through 607 are standard manuscript boxes and all boxes 608 and higher are record center cartons. But I think I could also add that thru bulk update.

**Comment by phoebeno** [comment]
oh, also, boxes up to Box 839 are at Mudd, and 840 and higher are at ReCAP.

**Comment by regineheberlein** [comment]
@phoebeno 
This is going to be a two-step process:
1. create the top_containers ("tc") in ASpace
2. link the top_containers to their respective archival objects ("ao")

Could you provide two separate spreadsheets to support those two processes please? 

For step 1, the data we need is:
- tc_type	
- tc_indicator	
- repo	
- barcode	
- ils_holding_id	
- location_uri	
- profile_uri
- restriction

For step 2, the data we need is:
- tc_barcode
- ao_uri

That should allow us to get the tc_uri for the new top_containers to link the two.

**Comment by phoebeno** [comment]
[Copy of AC107_Create_New_Containers.xlsx](https://github.com/pulibrary/aspace_helpers/files/10513711/Copy.of.AC107_Create_New_Containers.xlsx)

@regineheberlein here is the spreadsheet with the data for Step 1.

**Comment by regineheberlein** [comment]
Nvm, I found it--`/repositories/4`. I'll fix the spreadsheet.

**Comment by phoebeno** [comment]
@regineheberlein sorry I forgot the repo! Actually, I don't think I know where to find the uri for that. Is /repositories/4 the code for UA? Also, I meant to ask you about the ILS holding ID. What is it for? How should it be structured? All of the ones we have look like placeholders from the migration (to me) . . . Thanks!

**Comment by regineheberlein** [comment]
No worries @phoebeno, I already fixed it, see above! ^

**Comment by regineheberlein** [comment]
@phoebeno Can you QA on staging please? One thing to note--you won't be able to see the restrictions until the containers are linked, so don't worry if they say "false".

**Comment by regineheberlein** [comment]
About the ils_holding _id, that's up to you--it's not a required field, so it depends on your practices!

**Comment by phoebeno** [comment]
@regineheberlein OK, I entered some barcodes and got the correct boxes--they look good. When they get linked with AOs, will call numbers then get linked with these containers?

**Comment by regineheberlein** [comment]
Can you elaborate what you mean by "call numbers get linked"?

**Comment by phoebeno** [comment]
Right now the boxes have no associated call number--the resource/accession field is blank. Which I think is good, because they will have multiple call numbers from AC107.01 to AC107.16. So I am pretty sure that once AOs are linked, their call numbers will appear as part of those containers . . . I think I just talked myself through it.

**Comment by regineheberlein** [comment]
Right now, the containers are not linked. They will get all associated collection-level information from the ao once they're linked. 

If you go to "Manage Top Containers" and search for barcode 32101104566516, I've linked that one to an ao for you as an example.

**Comment by phoebeno** [comment]
Thanks! Great. Do you have any magical way to translate instance indicators, which is what I have on my spreadsheet, to barcodes? 
[AC107_Add_New_Containers.xlsx](https://github.com/pulibrary/aspace_helpers/files/10520057/AC107_Add_New_Containers.xlsx)

**Comment by regineheberlein** [comment]
I see, you don't actually have a mapping of barcode to archival object? Can you make one with an Excel formula?

**Comment by regineheberlein** [comment]
I'm going to split this ticket into two so we can keep the creation of the containers and the linking separate
