### ISSUE TITLE
schedule.rb does not create a log file

### ISSUE THREAD

**Issue by regineheberlein** [pulibrary/aspace_helpers#328]
**Describe the bug**
A log file should be created by schedule.rb. At a minimum, it should contain the starting and ending time stamps for aspace2alma. This doesn't happen.

**Comment by maxkadel** [comment]
I wonder if something like this would work? 

https://github.com/pulibrary/lib_jobs/blob/119ecd7e5127c80072780067d09d275a329a1a68/config/schedule.rb#L3
```ruby
set :output, '/opt/lib-jobs/shared/tmp/cron_log.log'
```

**Comment by regineheberlein** [comment]
Thanks! I'll try that. I'm also experimenting with logging from inside the Ruby script, as described in the first answer here: https://stackoverflow.com/questions/3018595/how-do-i-redirect-stderr-and-stdout-to-file-for-a-ruby-script

**Comment by regineheberlein** [comment]
This looks interesting, too: https://www.rubyguides.com/2019/08/logs-in-ruby/
