### ISSUE TITLE
AC107.01-AC107.16 link containers

### ISSUE THREAD

**Issue by regineheberlein** [pulibrary/aspace_helpers#344]
Next step after container creation in #320

**Comment by regineheberlein** [comment]
@phoebeno Just checking in on this--I started a new ticket for linking the containers here, see #320 ?

**Comment by phoebeno** [comment]
@regineheberlein working on it, but it may be early next week.

**Comment by regineheberlein** [comment]
Thanks for letting me know!

**Comment by phoebeno** [comment]
[AC107_Archival_Objects_for_RH.xlsx](https://github.com/pulibrary/aspace_helpers/files/10669470/AC107_Archival_Objects_for_RH.xlsx)
Regine, here is a spreadsheet to link the Archival Objects to the containers by barcode. This is a copy, so please feel free to delete all the columns you do not need. Please note that some objects are spread across two containers, so there is data in the second container column when that happens. Be in touch! Thank you many times.

**Comment by regineheberlein** [comment]
Hi @phoebeno , could I ask you to do a little more prep work to get me the input data I need without me having to immerse myself in or edit your spreadsheet? I only need one line per link, please, and just the two columns--the ao_uri and the barcode.

**Comment by phoebeno** [comment]
[AC107_Archival_Objects_for_RH.xlsx](https://github.com/pulibrary/aspace_helpers/files/10677604/AC107_Archival_Objects_for_RH.xlsx)
@regineheberlein can you work with this? If I delete the refID the sheet does not like it. 
Do you mean that everywhere there is a second barcode, it cannot be on the same line but you need me to make a new line for it?

**Comment by regineheberlein** [comment]
Yes please, if you could! Static data in two columns, as CSV (preferred) or Excel (which I'll save as CSV). 

Column A has a formula--just copy and paste to a new column as text, that will allow you to delete the columns it depends on. :-)

**Comment by phoebeno** [comment]
[AC107_Archival_Objects_for_RH.xlsx](https://github.com/pulibrary/aspace_helpers/files/10677966/AC107_Archival_Objects_for_RH.xlsx)
@regineheberlein

**Comment by regineheberlein** [comment]
@phoebeno These are now linked in staging (minus the barcodes that exist on prod already but not on staging), can you take a look?

**Comment by phoebeno** [comment]
@regineheberlein these look good! So are you saying that where barcodes are only in prod, like Box 24, those will be linked later?

**Comment by regineheberlein** [comment]
They were skipped on staging since they don't exist there. If they exist on prod, they'll be linked by the same process.

**Comment by regineheberlein** [comment]
@phoebeno 
This just finished on prod.

**Comment by phoebeno** [comment]
@regineheberlein cheers cheers cheers! you are my hero and the hero of us all!
