### ISSUE TITLE
update use statements

### ISSUE THREAD

**Issue by phoebeno** [pulibrary/aspace_helpers#354]
### We are coming back to the project to update all of the use statements for all repositories in bulk. We corresponded about this Feb-March 2022. @regineheberlein , before I fill out the rest of this form for the issue, might we schedule a time to meet? 

There are three basic use statements to be used. 1) UA only; 2) policy collections whose copyright is owned by PU; 3) all non UA, non-PU-owned collections. PLUS, of course, some unique exceptions (about 60 collections), particularly in MSS. The exception statements have not yet been re-written, but they can keep their old ones for the time being. 

Can we do this work in batches by repository? 

### Source of the data to be imported or updated
A link to a spreadsheet or similar containing the URI's you need edited and the fields you want imported or changed. Please don't submit "living" spreadsheets for this purpose and and limit the columns in the spreadsheet to data needed for the import.

### Implementation notes, if any
Describe any factors that might affect the data update, e.g. does existing data need to be checked first? Does the successful import depend on other operations, e.g. deletions or other steps that need to be completed first?

**Comment by regineheberlein** [comment]
See #142

**Comment by regineheberlein** [comment]
capturing from discussion:
- we will need to apply 3 different types of boilerplate
- one distinct boilerplate each on univarchives and mss (and everything else?
- two boilerplates for publicpolicy, depending on their copyright status
- Phoebe will supply a spreadsheet with uri's for publicpolicy

**Comment by regineheberlein** [comment]
Hi Phoebe, just checking in on this!

**Comment by phoebeno** [comment]
Thank you for checking! Argh, I went into another holding pattern with Sara checking on the language. It's a question of whether we can replace "photocopies" with "copies"!!! She is working on it, and as soon as I know I will pass it on. BUT, for your planning purposes, also know that I am out March 15-21, so I imagine it will be after that.

**Comment by phoebeno** [comment]
Hi @regineheberlein -- Sara says she will give me the correct language by the end of this week. I wanted to check, for the 50-some statements in mss and TC that are unique, can you leave them OUT of the bulk update, or do you need to update ALL and then re-input the unique statements with a spreadsheet that contains each unique statement? Thanks!

**Comment by regineheberlein** [comment]
Hi @phoebeno ,

we can do it either way. Both methods require that you give me a list of the 50+ "special" collections, either to leave out of the first iteration or to treat differently in the same go. But if the question is whether the 50 special ones are necessarily holding up the project, then the answer is no--we can do the others first and then come back to these!

**Comment by regineheberlein** [comment]
@phoebeno Are you all still working on this or should we close this ticket?

**Comment by phoebeno** [comment]
Yes! Working! This is at last the time! Thank you for the reminder.

**Comment by regineheberlein** [comment]
Ok, thanks for confirming!

**Comment by regineheberlein** [comment]
Hi @phoebeno , any news on this?

**Comment by phoebeno** [comment]
It is in my deep-deep-procrastination backlog. I will work on them next week! Thank you.

**Comment by regineheberlein** [comment]
@phoebeno Thanks for sending this along! After reviewing the spreadsheet, I'm not entirely clear what the action items are. Can you confirm that it's this:
- use the first tab for PPP. Run over the uri's on the tab and update userestricts to the corresponding value in column E
- use the second tab for MSS. Run over everything EXCEPT the uri's on the second tab. 

Is that correct? And, if so, a question: What should the mss notes be updated to?

**Comment by phoebeno** [comment]
Hi @regineheberlein. I have also created a doc[https://docs.google.com/document/d/1CKzb4QK4HmxsgMFhiANVVoW5oADy2X3ymjkn8BY1J1s/edit](url) that attempts to lay out the three statements and where they go.

**Comment by regineheberlein** [comment]
- [ ] univarchives
  boilerplate:
  link to exception uri's + text: 
- [ ] ppp
  boilerplate:
  link to exception uri's + text: 
- [ ] mss
  boilerplate:
  link to exception uri's + text: 
- [ ] rarebooks
  boilerplate:
  link to exception uri's + text: 
- [ ] cotsen
  boilerplate:
  link to exception uri's + text: 
- [ ] lae
  boilerplate:
  link to exception uri's + text: 
- [ ] eng
  boilerplate:
  link to exception uri's + text: 
- [ ] selectors
  boilerplate:
  link to exception uri's + text: 
- [ ] ga
  boilerplate:
  link to exception uri's + text: 
- [ ] ea
  boilerplate:
  link to exception uri's + text:

**Comment by regineheberlein** [comment]
Thanks @phoebeno for compiling this!

**Comment by regineheberlein** [comment]
@phoebeno I'm assuming that you want the paragraphs in `<p>` tags as we've done with other long notes, let me know if that's not the case here!

**Comment by regineheberlein** [comment]
Implementation note: 

I'll run the default note over all resource records in each corresponding repo first, then I'll go back and run the exceptions.

(cc @phoebeno)

**Comment by regineheberlein** [comment]
Modified input files: replaced double quotes with single quotes, add `<p>`.

**Comment by regineheberlein** [comment]
@phoebeno I'm noticing that diacritics and other special characters are mangled in the mss CSV. I'm running it as-is in staging now, but let me know if you want to give me an amended CSV before running it on prod.

**Comment by phoebeno** [comment]
Aha! Diacritics! Yes, let me have a look.

**Comment by regineheberlein** [comment]
I found a way! Though now I'm also fighting with hard line breaks in mss that mess up the CSV also. Stay tuned.

**Comment by phoebeno** [comment]
Oh, I did not see your comment, but I edited the diacritics and attached a new version of the spreadsheet if you need it. Let me know if I can help further with the mss sheet.

**Comment by regineheberlein** [comment]
I ended up doing manual cleanup on the line breaks, and I've resolved the special character issue. The resulting input file for all exceptions is attached for your review. (It's best viewed in a text editor (e.g. Oxygen)).

[exceptions.csv](https://github.com/pulibrary/aspace_helpers/files/13567380/exceptions.csv)

**Comment by regineheberlein** [comment]
@phoebeno ASpace-staging is ready for your review.

**Comment by phoebeno** [comment]
Thank you! I am taking a break before review.

**Comment by regineheberlein** [comment]
Done after getting the green light from @phoebeno ; closing this ticket.
