### ISSUE TITLE
test new ASpace plugin for component-level aspace2alma

### ISSUE THREAD

**Issue by regineheberlein** [pulibrary/aspace_helpers#359]
The plugin is up at:
[https://github.com/hudmol/as_marcao](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fhudmol%2Fas_marcao&data=05%7C01%7Cheberlei%40princeton.edu%7C28d6c859b84e4526111708db2ff355b9%7C2ff601167431425db5af077d7791bda4%7C0%7C0%7C638156494400364869%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=9AndjySuzMC%2B1dv5hgkWuXOFZcR8mk5Brh0Yr9pMRUs%3D&reserved=0)

The first test release is available here:
[https://github.com/hudmol/as_marcao/releases/tag/v0.1](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fhudmol%2Fas_marcao%2Freleases%2Ftag%2Fv0.1&data=05%7C01%7Cheberlei%40princeton.edu%7C28d6c859b84e4526111708db2ff355b9%7C2ff601167431425db5af077d7791bda4%7C0%7C0%7C638156494400364869%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=pbKT7zuN5OcHj11xflxA56toWvhAairGKb3c3NoU%2BEc%3D&reserved=0)

**Comment by regineheberlein** [comment]
The plugin is installed.

**Comment by regineheberlein** [comment]
Another currently-installed plugin, `user_defined_in_basic`, is configured to override the User Defined Fields section needed for the new plugin. I'm currently checking in with stakeholders to make sure we can change the config to move `boolean_1` to the Basic Information section without breaking anything.

**Comment by regineheberlein** [comment]
We can safely move boolean_1 to Basic Information and leave the User Defined Section hidden, based on the current config for `user_defined_in_basic` that Blake sent me:

```AppConfig[:user_defined_in_basic] = {
  "accessions" => ["date_1", "text_1", "text_2", "text_3", "boolean_1", "boolean_2", "boolean_3", "date_2", "string_1", "string_2", "string_3",  "string_4", "real_1", "real_2", "enum_2"],
  "digital_objects" => [],
  "resources" => [],
  "hide_user_defined_section" => true
}
```
So we're only using the user-defined fields in the Accessions module to begin with, which should make enabling boolean_1 in the Resources module uncontroversial. 

Waiting for ASpace-ops to confirm.

**Comment by regineheberlein** [comment]
From what I'm seeing now that boolean_1 is exposed in the Resource record, it appears that there may be a total of 3 booleans available across modules, rather than per module as I had assumed. I'm seeing the checkbox with a label "Notable", which is what is has in the Accessions module.

I'm clarifying with Lyrasis.

**Comment by regineheberlein** [comment]
From the .yml that Blake sent it appears that the fields are distinct but the labels are, confusingly, the same. It looks as if the config for accessions has simply been copied to the other modules--including a missing enum_1. I've asked Blake to change the label on staging Resources boolean_1 to confirm.

**Comment by regineheberlein** [comment]
Meanwhile it sounds like ADAPT is not using all the booleans defined in Accessions and we can possibly use on of those.

**Comment by regineheberlein** [comment]
https://github.com/archivesspace/archivesspace/blob/master/common/locales/en.yml#L11

**Comment by regineheberlein** [comment]
We've identified a big in user_defined_in_basic that's causing this behavior. HM has pushed a new version for us that is now installed on staging, and testing as_marcao can proceed.

**Comment by regineheberlein** [comment]
First attempt failed, likely due to a credentials issue on lib-sftp. Following up.

**Comment by regineheberlein** [comment]
John K updated the firewall rules

**Comment by regineheberlein** [comment]
Meanwhile, I'm now documenting config choices in https://github.com/pulibrary/aspace-config

**Comment by regineheberlein** [comment]
Failed again; we were missing the domain from the server name

**Comment by regineheberlein** [comment]
Failed again, John K will check logs for lib-sftp-staging1

**Comment by regineheberlein** [comment]
It failed yesterday; I suspected that it needed a new data update which I had failed to create. I created a data update to force a fresh export overnight, which it did, but the hand-off to sftp is still failing.

**Comment by regineheberlein** [comment]
It failed again. This time we were able to narrow it down to a timeout issue.

1. aspace finds sftp, so it's not a Docker issue
2. sftp munges the authentication for a while (not sure why)
3. aspace gets impatient and walks away.

The part where aspace walks away is not aspace proper but a gem that the plugin uses, net-sftp, which looks like it takes a timeout parameter: https://github.com/net-ssh/net-sftp/issues/129. I'll ask James about it.

**Comment by regineheberlein** [comment]
James has posted a new version that allows control of the timeout parameter, and Blake is going to update the plugin for us on staging.

**Comment by kevinreiss** [comment]
Plugin is having trouble connecting to the lib-sftp. Adjusting timeounts.

**Comment by regineheberlein** [comment]
After increasing the timeout parameter, the connection is still failing.

From Blake:

> Logs attached.
> Something interesting I caught this time, I did "sftp" once, and it took about 48 seconds to return anything, but I forgot the "-vvvv" so I stopped that and did it again with the Vs and it connected instantly. No big strange pause. That first connection woke something up?
>  
> mtr in case that helps

 
```
                                                                                       My traceroute  [v0.93]
ip-10-14-1-180 (10.14.1.180)                                                                                                                                               2023-05-03T14:02:56+0000
Keys:  Help   Display mode   Restart statistics   Order of fields   quit
                                                                                                                                                           Packets               Pings
 Host                                                                                                                                                    Loss%   Snt   Last   Avg  Best  Wrst StDev
 1. (waiting for reply)
 2. (waiting for reply)
 3. (waiting for reply)
 4. 241.0.2.64                                                                                                                                            0.0%    12    0.2   0.2   0.2   0.3   0.0
 5. 108.166.236.8                                                                                                                                         0.0%    12    0.2   0.4   0.2   2.0   0.5
 6. 108.166.236.25                                                                                                                                        0.0%    12    0.2   0.2   0.2   0.2   0.0
 7. 240.192.3.147                                                                                                                                         0.0%    12    0.2   0.2   0.2   0.2   0.0
 8. 108.166.236.25                                                                                                                                        0.0%    12    0.2   0.2   0.2   0.2   0.0
 9. 108.166.236.6                                                                                                                                         0.0%    12    0.2   0.2   0.2   0.3   0.0
10. 242.0.51.17                                                                                                                                           0.0%    12    3.1   0.9   0.3   3.1   0.8
11. 100.95.1.29                                                                                                                                           0.0%    12    0.8   0.5   0.3   0.9   0.2
12. 100.100.2.108                                                                                                                                         0.0%    12    0.4   2.6   0.3  26.9   7.7
13. 100.92.31.56                                                                                                                                          0.0%    12    8.0   9.0   7.3  19.5   3.5
14. 100.92.26.52                                                                                                                                          0.0%    12    6.2   6.7   6.2   7.6   0.4
15. 100.92.26.69                                                                                                                                          0.0%    12    8.5   8.6   7.8  12.3   1.3
16. 100.92.28.68                                                                                                                                          0.0%    11    6.4   6.8   6.4   7.3   0.3
17. 100.92.28.49                                                                                                                                          0.0%    11    7.1   6.8   6.4   7.3   0.3
18. 52.93.131.73                                                                                                                                          0.0%    11    6.9   6.2   5.7   6.9   0.4
19. 100.92.127.120                                                                                                                                        0.0%    11    7.4   8.3   6.2  14.5   2.8
20. 100.92.127.135                                                                                                                                        0.0%    11    7.3   8.0   7.3  12.3   1.5
21. 100.92.125.134                                                                                                                                        0.0%    11    6.2   6.3   5.8   6.7   0.4
22. 100.92.125.121                                                                                                                                        0.0%    11    6.8   8.3   6.3  18.1   3.8
23. 100.92.133.9                                                                                                                                          0.0%    11    6.3   7.8   6.3  16.4   3.1
24. 240.1.228.12                                                                                                                                         60.0%    11  764.5 751.5 744.6 764.5   8.9
25. 242.4.195.193                                                                                                                                         0.0%    11    7.6   8.7   7.6  15.1   2.2
26. 52.95.52.11                                                                                                                                           0.0%    11    6.2   6.6   6.1   8.0   0.7
27. 99.82.178.93                                                                                                                                          0.0%    11    9.7  10.3   9.6  11.4   0.6
28. fourhundredge-0-0-0-20.4079.core1.seat.net.internet2.edu                                                                                              0.0%    11   84.1  83.3  82.5  84.1   0.4
29. fourhundredge-0-0-0-0.4079.core1.salt.net.internet2.edu                                                                                               0.0%    11   81.7  81.2  80.2  82.4   0.6
30. fourhundredge-0-0-0-0.4079.core1.denv.net.internet2.edu                                                                                               0.0%    11   81.8  83.2  81.8  84.8   0.9
```

**Comment by regineheberlein** [comment]
HM needs to provide a stable IP for Francis to put on the allow list

**Comment by regineheberlein** [comment]
Stable IP is now on our allow list. HM will continue testing Monday.

**Comment by regineheberlein** [comment]
HM found an issue with the sftp gem and has posted a fix; we've asked Blake to install.

HM is also reporting a directory permissions issue that we cannot reproduce locally. We'll proceed with testing as-is, and if Lyrasis runs into the same issue, we'll try a symbolic link from the directory HM was able to write to.

**Comment by regineheberlein** [comment]
HM found that lib-aspacesftp@pu.win.princeton.edu fails but lib-aspacesftp succeeds. After changing the config, we're observing that an empty export file made it to the sftp server. This is most likely because there were no changes to export at the time Blake tried it. We'll wait for the scheduled export.

**Comment by regineheberlein** [comment]
Scheduled export succeeded.

**Comment by regineheberlein** [comment]
HM has posted updates to improve the accuracy of the incremental export and report page. We're now on v.0.5.

**Comment by regineheberlein** [comment]
This is now working from aspace staging to sftp staging. Next steps:

- [ ] test current export file in Alma Sandbox. This needs to be done manually since the Sandbox doesn't allow scheduled jobs.
- [ ] disable plugin in staging
- [ ] upgrade user_defined_in_basic in prod
- [ ] update config yml in prod
- [ ] enable plugin in prod--this will be done on or after the sftp migration Wed 5/24

**Comment by regineheberlein** [comment]
```
May 30, 2023 10:22:00 PM net.schmizz.sshj.transport.random.JCERandom <init>
INFO: Creating new SecureRandom.
May 30, 2023 10:22:01 PM net.schmizz.sshj.transport.TransportImpl sendClientIdent
INFO: Client identity string: SSH-2.0-SSHJ_0.30.0
May 30, 2023 10:22:01 PM net.schmizz.sshj.transport.TransportImpl init
INFO: Server identity string: SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.7
W, [2023-05-30T22:22:01.988346 #754]  WARN -- : Thread-9746: marcao: Upload to SFTP failed:
W, [2023-05-30T22:22:02.000021 #754]  WARN -- : Thread-9746: marcao: Will retry 9 more times
May 30, 2023 10:22:32 PM net.schmizz.sshj.transport.random.JCERandom <init>
INFO: Creating new SecureRandom.
May 30, 2023 10:22:32 PM net.schmizz.sshj.transport.TransportImpl sendClientIdent
INFO: Client identity string: SSH-2.0-SSHJ_0.30.0
May 30, 2023 10:22:32 PM net.schmizz.sshj.transport.TransportImpl init
INFO: Server identity string: SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.7
W, [2023-05-30T22:22:32.502190 #754]  WARN -- : Thread-9746: marcao: Upload to SFTP failed:
W, [2023-05-30T22:22:32.502488 #754]  WARN -- : Thread-9746: marcao: Will retry 8 more times
May 30, 2023 10:23:02 PM net.schmizz.sshj.transport.random.JCERandom <init>
INFO: Creating new SecureRandom.
May 30, 2023 10:23:02 PM net.schmizz.sshj.transport.TransportImpl sendClientIdent
INFO: Client identity string: SSH-2.0-SSHJ_0.30.0
May 30, 2023 10:23:02 PM net.schmizz.sshj.transport.TransportImpl init
INFO: Server identity string: SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.7
W, [2023-05-30T22:23:03.017115 #754]  WARN -- : Thread-9746: marcao: Upload to SFTP failed:
W, [2023-05-30T22:23:03.017412 #754]  WARN -- : Thread-9746: marcao: Will retry 7 more times
May 30, 2023 10:23:33 PM net.schmizz.sshj.transport.random.JCERandom <init>
INFO: Creating new SecureRandom.
May 30, 2023 10:23:33 PM net.schmizz.sshj.transport.TransportImpl sendClientIdent
INFO: Client identity string: SSH-2.0-SSHJ_0.30.0
May 30, 2023 10:23:33 PM net.schmizz.sshj.transport.TransportImpl init
INFO: Server identity string: SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.7
```

**Comment by regineheberlein** [comment]
Blake still thinks it's a timeout issue, based on his logs. Asked him to check that we're on v.05 and the marcao_sftp_timeout parameter is set to 60.

**Comment by regineheberlein** [comment]
During testing with Blake, we eliminated all the diverging plugins from prod and found no difference in behavior.

Blake identified a second spot where the user name may need to be set; will try after hours tonight.

**Comment by regineheberlein** [comment]
Working now from aspace prod > lib-sftp-staging1

Will ask Blake to change setting to lib-sftp-prod1

**Comment by regineheberlein** [comment]
This is now working from aspace staging to sftp staging. Next steps:

- [x] test current export file in Alma Sandbox. This needs to be done manually since the Sandbox doesn't allow scheduled jobs.
- [x] disable plugin in staging
- [x] upgrade user_defined_in_basic in prod
- [x] update config of user_defined_in_basic in prod
- [x] update config yml in prod
- [x] enable plugin in prod
- [x] add aspace prod to sftp allow list
- [x] switch plugin in prod from sftp staging to sftp prod--this will be done on or after the sftp migration Wed 5/24
- [ ] enable Alma import profile

**Comment by regineheberlein** [comment]
Working now from aspace prod > lib-sftp-staging1

Waiting for the Alma import job to be enabled.

**Comment by regineheberlein** [comment]
Alma job is enabled. I will close this ticket after checking the import tomorrow morning.
