### ISSUE TITLE
re-imported components trigger the "multiple items" label in the XSL-FOP

### ISSUE THREAD

**Issue by regineheberlein** [pulibrary/aspace_helpers#399]
**Describe the bug**
From aspace-help: 

I had imported a spreadsheet of archival objects, and printed off folder labels through oXygen. Then I imported another spreadsheet with my next set of archival objects, but I had accidentally left the same archival objects I already imported, so I reimported a mix of archival objects that were already in Aspace. when I did the folder label transformation scenario, some of the titles of the folders changed to "Multiple Items" if they were for archival objects I had already imported. But in Aspace, each component still looks like one component without duplicated information anywhere. But I'm wondering, since I accidentally imported a spreadsheet of archival objects twice, did it do something to the XML?

**Steps to replicate**
Steps to reproduce the behavior, if applicable.

**Expected behavior**
The print label should only print a single item

### Impact of this bug
This results in wrong folder labels

**Comment by regineheberlein** [comment]
I'm speculating that the re-import created duplicate holdings, but this is to be confirmed

**Comment by regineheberlein** [comment]
The affected collection is C0183

**Comment by amycvo** [comment]
There are no identifiable duplicates in the resource record, or in the Top Container view. 
![Screenshot (56)](https://github.com/pulibrary/aspace_helpers/assets/75688375/3b548d54-35b8-42ee-b7d9-3c2531df7525)
![Screenshot (57)](https://github.com/pulibrary/aspace_helpers/assets/75688375/95f93943-1c14-41b4-a7a7-40c4c840876b)

**Comment by amycvo** [comment]
Here is what happens with running the folder labels transformation scenario: 
![Screenshot (58)](https://github.com/pulibrary/aspace_helpers/assets/75688375/f45b5690-67d8-40f6-aa93-1c2f3a795d45)

**Comment by amycvo** [comment]
It looks like the XML for the second set of accidentally imported archival objects is repeated in the file: 
![Screenshot (59)](https://github.com/pulibrary/aspace_helpers/assets/75688375/68e56148-bcd2-465e-89b8-f3f5669016df)

**Comment by regineheberlein** [comment]
If you look at [Subseries 1C](https://aspace.princeton.edu/staff/resources/3755#tree::archival_object_1479557), the two duplicate series are there at the end. 

Can you simply delete them from there? If the situation is more complex, let me know and I'll help!

**Comment by amycvo** [comment]
Wow, I totally missed that they nested there! Thank you for being so thorough, Regine!!!!!!!!

**Comment by regineheberlein** [comment]
Thank you for providing all the background information--that helped a lot!!
