### ISSUE TITLE
CPF export lacks required maintenance history elements

### ISSUE THREAD

**Issue by regineheberlein** [pulibrary/aspace_helpers#41]
"control"=>{"recordId"=>":agents:people:10891",
"maintenanceStatus"=>"revised",
"maintenanceAgency"=>{"agencyName"=>"University Archives"},
"maintenanceHistory"=>nil}

**Comment by regineheberlein** [comment]
```
"control"=>{"recordId"=>":agents:people:10891",
"maintenanceStatus"=>"revised",
"maintenanceAgency"=>{"agencyName"=>"University Archives"},
"maintenanceHistory"=>nil}
```

**Comment by regineheberlein** [comment]
Other fields could be populated with default values.
```
<maintenanceEvent>
  <eventType>revised</eventType>
  <eventDateTime standardDateTime="2021-08-13T02:31:14Z"/>
  <agentType>person</agentType>
  <agent>admin</agent>
  <eventDescription>Updated by staff.</eventDescription>
</maintenanceEvent>
```

**Comment by regineheberlein** [comment]
required elements are:
RecordID — has to be an NMToken
MainenanceHistory (one or more maintenance events)
MaintenanceStatus --> this is in RecordInfor
MaintenanceAgency --> AgencyName

**Comment by regineheberlein** [comment]
This is currently blocked because the current release of ASpace uses an invalid (and not locally editable) controlled value list for MaintenanceStatus. Need to defer until the next release (May 2022).

**Comment by regineheberlein** [comment]
@faithc Is this still an issue?

**Comment by regineheberlein** [comment]
@faithc Is this still needed or can we close the issue?

**Comment by regineheberlein** [comment]
So would you like me to work on this? Or no?

**Comment by faithc** [comment]
Not at this point, no. Thanks.

**Comment by regineheberlein** [comment]
Re-opening after checking in with @Will-Clements.

**Comment by regineheberlein** [comment]
This is ready for review on staging

**Comment by regineheberlein** [comment]
Approved, now running on prod (in chunks so we don't slow down the server during business hours)
