### ISSUE TITLE
We need a top_container report to support the ReCAP project

### ISSUE THREAD

**Issue by regineheberlein** [pulibrary/aspace_helpers#414]
### User story
From Faith via Will (on Slack)
```
priority at the moment, because they are moving ahead with the project and need this report to do it
```

### Resource record URI's to pull this data from:

tab 1 of this spreadsheet:
https://docs.google.com/spreadsheets/d/1C3lnMez_IuiY6O0D-vmd__gk7CUstCWj_y1wzdrshZU/edit?usp=sharing

### Fields to include:

```
top container data, specifically:
Call number
Collection title
Container type
Indicator
Barcode
Container profile
Locations Note
```

**Comment by regineheberlein** [comment]
Are you able to provide resource uri's?

**Comment by faithc** [comment]
I forget--how would I go about doing this?

**Comment by regineheberlein** [comment]
I don't know what you mean by "generate"? ASpace assigns them when you create a record. It's what identifies the record for purposes of creating the report you're requesting, so you just need to include them in your report request like always please.

<img width="1028" alt="Screenshot 2023-08-30 at 1 45 07 PM" src="https://github.com/pulibrary/aspace_helpers/assets/5940563/c6457dd6-9511-4d1c-bc69-5e68e32e14ef">

**Comment by faithc** [comment]
Yes. I forget if there's a way to generate a report or export this information since this the request includes about 425 collections.

**Comment by regineheberlein** [comment]
@faithc please see the attached report

[top_containers_by_collection.csv](https://github.com/pulibrary/aspace_helpers/files/12500902/top_containers_by_collection.csv)

**Comment by faithc** [comment]
Thank you!

**Comment by regineheberlein** [comment]
@faithc I uploaded a new copy of the report above--the previous one had a bug. Can you look this one over nd make sure that it looks as expected?
