### ISSUE TITLE
add missing barcodes to ASpace from Alma/SCSB

### ISSUE THREAD

**Issue by regineheberlein** [pulibrary/aspace_helpers#423]
Related to #421 and blocking #397

**Comment by Will-Clements** [comment]
I've worked through the initial report and divided it into to categories, which are the first two tabs in [this spreadsheet](https://docs.google.com/spreadsheets/d/1cXvlZw5VeONl9muNQi8_P7b9IeEVJfpgxTIyr6KNT_A/edit?usp=sharing): "Simple barcode imports," and "Problems to solve." Simple barcode imports are the ones I believe are just a matter of getting the barcodes into ASpace. Problems to solve are knottier issues that are going to require some investigation.
The remaining tabs are each a collection, and contain barcodes and corresponding box numbers exported from Alma.

The next step in this cleanup would be to do the simple barcode imports. To support that, I'm going to add here a list of call numbers, and if you could please go to the tab associated with each call number in the spreadsheet, and import the barcodes therein to ASpace, that would be great! Note that there are call numbers in those tabs that are not ready to import yet, so please just use the list of call numbers below.

Then once we've resolved the "Problems to solve" we may give you additional call numbers to import bar codes to ASpace.

some of these issues may be complicated and take time to sort out, so unfortunately it may be a bit before we can implement the new process you've designed.

MC165
AC240
AC283
AC154
AC161
C0129
TC019
TC022
TC059
TC064
TC091
TC110
TC111
TC112
LAE119

**Comment by regineheberlein** [comment]
Ok! I've added checkboxes to the above list to keep track.

**Comment by regineheberlein** [comment]
Strategy:
1. get resource uri's for relevant collections
2. for each resource, get all top_container records: uri, type, indicator
3. match against Alma spreadsheet on type/indicator
4. import barcode

**Comment by regineheberlein** [comment]
@Will-Clements We have discrepancies between the container indicators in Alma and those in ASpace (e.g. leading zeroes). This is preventing a match on container type + indicator. 

I've created a new tab in your Google sheet with the ASpace top_containers for the selected collections; could you check the numbering in the Alma item records and, if different from ASpace, add it to column F please?

**Comment by regineheberlein** [comment]
We will start importing barcodes incrementally

**Comment by regineheberlein** [comment]
@Will-Clements 
The following from the simple imports tab either don't match even after harmonization or are not in Alma; can you take a look and let me know how we'll handle these?
|aspace_barcode|aspace_enum|location|eadid|aspace_match_string|alma_match_string|aspace_uri|alma_barcode|
----|----|----|----|----|----|----|----|																		
AC283_add6	|box 167	|scarcpph	|AC283	|AC283box 167	|AC283box 167	|/repositories/4/top_containers/118932	|#N/A																			
AC283_add7	|box 314	|scarcpph	|AC283	|AC283box 314	|AC283box 314	|/repositories/4/top_containers/118933	|#N/A																			
|C0129_n74	|box 820	|scarcpxm	|C0129	|C0129box 820	|C0129box 820	|/repositories/5/top_containers/98229	|#N/A																			
MC165_n207	|box 263	|scarcpph	|MC165	|MC165box 263	|MC165box 263	|/repositories/3/top_containers/36612	|#N/A																			
MC165_add305	|box 268	|scarcpph	|MC165	|MC165box 268	|MC165box 268	|/repositories/3/top_containers/119243	|#N/A																			
MC165_n246	|box 335	|scarcpph	|MC165	|MC165box 335	|MC165box 335	|/repositories/3/top_containers/36651	|#N/A
