### ISSUE TITLE
something went wrong with the new aspace2alma

### ISSUE THREAD

**Issue by regineheberlein** [pulibrary/aspace_helpers#443]
Placeholder issue in case DACS needs it while Regine is out.

See [this chart](https://github.com/pulibrary/lib_jobs/tree/main/docs/aspace2alma) for an overview of the integration steps.

The script is called `get_MARCxml_with_items.rb` and is scheduled to run nightly.

### Things to check if the file didn't reach Alma

- [ ] check the datestamp of the `MARC_out.xml` file on lib-jobs-prod2 see /opt/aspace_helpers/current/reports/aspace2alma

      (did the export run?)
- [ ] check `log_err.txt` and `log_out.txt` on lib-jobs-prod2 see /opt/aspace_helpers/current/reports/aspace2alma

      (did the export finish without errors?
      log_err will have error messages, if any; log_out will have the progress of the export with start and end times.)
- [ ] check the datestamp of the `MARC_out.xml` file and/or log files on lib-
      sftp-prod1 see /alma/aspace

      (did the file get transferred from lib-jobs to lib-sftp?)
- [ ] check the datestamp of the `ASpace to Alma With Items` import profile

      Admin > Monitor Jobs > `ASpace to Alma With Items`

### If something else goes wrong

Disable the `ASpace to Alma With Items` import profile to suspend further imports to Alma while troubleshooting. (You may need the Alma team to do this.)

**Comment by maxkadel** [comment]
Using the Net::SFTP `rename!`, you cannot rename something to an existing filename. [PR to add a datestamp](https://github.com/pulibrary/aspace_helpers/pull/444), rather than renaming to `_old`. This means we will also probably need to add a cleanup step, because the file sizes are substantial.

**Comment by maxkadel** [comment]
With the datestamp fix, the job ran fine on lib-jobs-staging2. I think we're good to deploy to production.
