### ISSUE TITLE
remove PUL as creator

### ISSUE THREAD

**Issue by regineheberlein** [pulibrary/aspace_helpers#46]
list of collections https://docs.google.com/spreadsheets/d/1wYzXyWBMoElPUntLX7pzoECeiMpkAxwQ/edit#gid=1206104948

**Comment by regineheberlein** [comment]
uri == "/agents/corporate_entities/2028"
'role' == "creator" 
'relator' == "col"

**Comment by regineheberlein** [comment]
uri could also be 3961

**Comment by christinach** [comment]
closed by https://github.com/pulibrary/aspace_helpers/pull/120

**Comment by regineheberlein** [comment]
Running based on new input file provided by AAWG
