### ISSUE TITLE
remove/merge near-duplicate subject headings

### ISSUE THREAD

**Issue by regineheberlein** [pulibrary/aspace_helpers#466]
### User story

These headings are causing db validity issues

### Source of the data to be imported or updated
https://docs.google.com/spreadsheets/d/1JXdyoA1ytdCXL0XRP40bsHpgTtBza0JziQ42ngwZHxY/edit#gid=1809559674

**Comment by regineheberlein** [comment]
Step 1: merge "uncontrolled", "LAE", "ingest" into "local"

**Comment by regineheberlein** [comment]
Having completed this process, the following source values are in production:
```
local
nad
ulan
viaf
lcnaf
lcsh
snac
```

**Comment by cathyprinceton** [comment]
Please consult the [source codes](https://www.loc.gov/standards/sourcelist/subject.html) for $2 for subjects (MARC 6XX fields) and the [source codes](https://www.loc.gov/standards/sourcelist/name-title.html) for $2 in names and title headings (1XX/7XX/8XX fields). Hope this helps.

**Comment by regineheberlein** [comment]
@Will-Clements 
SC will need to consult the source codes list please to identify which ones are still invalid. We are aware of `viaf`, but there may be others.
