### ISSUE TITLE
"Princeton University" should be a corporate body Agent in ASpace

### ISSUE THREAD

**Issue by regineheberlein** [pulibrary/aspace_helpers#480]
### User Story -- briefly describe the problem:
Catalogers observe that there are large numbers of instances where "Princeton University" inappropriately maps to a 650.

Background: These were tagged in EAD as `subject` and migrated to the Subjects area of ArchivesSpace: https://aspace.princeton.edu/staff/subjects/17020. That area maps to 650.

### Example record(s) where you observed this problem
- MMSID: 
- Record (cut&paste): 

### What should that Record look like instead?
- Record: `610 20 Princeton University`
- Explanation (if applicable): 

### Impact
- How many records are affected by this issue?:
- OCLC error level:
  - [ ] Minor
  - [x] Critical
  - [ ] Severe

### Anything else we may need to know to tackle this issue:
This issue was submitted by the Authorities DQ group in a meeting on 11/30 (also see https://docs.google.com/document/d/1-mcVnq9UCgBluq8ZqYgFmVcn2Z44EP9a/edit).

**Comment by regineheberlein** [comment]
This involves
1. retrieving the record
2. retrieving all records linking to that record
3. transforming the record to a corporate body Agent record
4. posting the record to Agents
5. relinking all records to the new Agent record
6. deleting the Subject record

**Comment by cathyprinceton** [comment]
**Example record(s) where you observed this problem**

MMSID: 9968951883506421 ((PULFA)AC394)
Record (cut&paste):
650 _0 |a Princeton University |x Golf |x History
650 _0 |a Princeton University |x Sports |x History

What should that Record look like instead?
610 20 |a Princeton University |x Golf |x History
610 20 |a Princeton University |x Sports |x History

MMS ID:  99127176245206421  ((PULFA)C0140_c72735-08369)
Record:
651 _0 |a Parthenon (Athens, Greece) |x Photographs.          (Note: This is a building, not a geographic name)

What should that Record look like instead?
610 20 |a Parthenon (Athens, Greece) |v Photographs.                ($v is form subdivision, should also be updated.)

How many records are affected by this issue?:  Don't know. (hundreds)
OCLC error level:

-[ ] Minor
-[x] Critical
-[ ]Severe

**Comment by regineheberlein** [comment]
Thank you @cathyprinceton !

**Comment by regineheberlein** [comment]
Some of the Princeton headings exist as both subjects and agents; in some cases they are linked to the same descriptive record (coming, no doubt, from EAD `<subject>` and `<corpname>` respectively). There is also a significant amount of duplication within the Agent headings that needs cleanup.

**Comment by regineheberlein** [comment]
Implementation note: there is no endpoint to retrieve objects that link to an Agent or Subject by agent_id or subject_id. This means one has to go querying all resource/ao/do/event/accession records, which is expensive.

**Comment by regineheberlein** [comment]
Implementation note: The current logic in aspace2alma is: if the double dash is followed by numbers, make it a date subdivision, else make it a topical subdivision.

Checking for form (or, for that matter, geographical) subdivisions would require terms dictionaries to check against, which is both expensive and not terribly robust.

**Comment by regineheberlein** [comment]
- [ ] Princeton University -- Students -- 20th century (8 links)
- [ ] Princeton University (1 link)
- [ ] Princeton University -- Alumni and alumnae.
- [ ] Princeton University -- Alumni and alumnae -- Photographs.
- [ ] Princeton University -- Buildings -- Photographs.
- [ ] Princeton University -- Carl A. Fields Center for Equality and Cultural Understanding.
- [ ] Princeton University -- Faculty -- 19th century.
- [ ] Princeton University -- Faculty -- 20th century -- Sources.
- [ ] Princeton University -- Faculty -- 20th century.
- [ ] Princeton University -- Faculty.
- [ ] Princeton University -- Golf -- History
- [ ] Princeton University -- History -- 20th century -- SourcesPrinceton University -- Songs and music.
- [ ] Princeton University -- Sports -- History
- [ ] Princeton University -- Sports -- Photographs.
- [ ] Princeton University -- Students -- 19th century.Princeton University -- Students.
- [ ] Princeton University -- Third World Center.
- [ ] Princeton University Faculty -- Photographs.
- [ ] Princeton University--Faculty--20th century--Manuscripts.
- [ ] Princeton University--Lacrosse
- [ ] Princeton University--Presidents--18th century
- [ ] Princeton University--Sports.
- [ ] Princeton University. -- Alumni and alumnae -- Photographs.
- [ ] Princeton University. -- Photographs.
- [ ] Princeton University. Athletic Association
- [ ] Princeton University. Office of Population Research.
- [ ] Princeton University. Theatre Intime.
- [ ] Princeton University. Triangle Club.
- [ ] Princeton University. Triangle Club.
- [ ] Princeton University. University Players.

**Comment by regineheberlein** [comment]
Closing. The Athletic Association record needs to be further investigated by SC.

**Comment by regineheberlein** [comment]
Re-linked the Athletic Association records in consultation with AAWG (and invaluable help from Dan Linke)
