### ISSUE TITLE
genre/form subdivision should map to $v

### ISSUE THREAD

**Issue by regineheberlein** [pulibrary/aspace_helpers#481]
### User Story -- briefly describe the problem:
Catalogers observe that genre/form subdivisions are inappropriately mapped to $x.

Background: This is due to EAD heading strings being split on `--` by aspace2alma in post-export processing, following the logic "if it's a date, put it in $y, else, put it in $x".

### Example record(s) where you observed this problem
- MMSID: 
- Record (cut&paste): 
  650 _0 African American abolitionists ǂy 19th century ǂx Correspondence.
  650 _0 Indians of North America ǂx Arizona ǂx Photographs

### What should that Record look like instead?
- Record:
  650 _0 African American abolitionists ǂy 19th century ǂv Correspondence.
  650 _0 Indians of North America ǂx Arizona ǂv Photographs
- Explanation (if applicable): 

### Impact
- How many records are affected by this issue?:
- OCLC error level:
  - [ ] Minor
  - [ ] Critical
  - [ ] Severe

### Anything else we may need to know to tackle this issue:
This issue was submitted by the Authorities DQ group in a meeting on 11/30 (also see https://docs.google.com/document/d/1-mcVnq9UCgBluq8ZqYgFmVcn2Z44EP9a/edit).

**Comment by regineheberlein** [comment]
@cathyprinceton will provide a list of terms.

**Comment by regineheberlein** [comment]
Ideally, we'll tackle this at the source by moving strings to the appropriate subfields.

**Comment by regineheberlein** [comment]
@cathyprinceton Just checking in--could you provide a list of terms to support this work?

**Comment by cathyprinceton** [comment]
Apologies! Yang is compiling a list of commonly used terms for archival materials. I'll send it to you by next Thursday (8/1).

**Comment by regineheberlein** [comment]
Run on staging for the three values above; waiting for stakeholder feedback.

**Comment by cathyprinceton** [comment]
Can we see some sample records from staging? (I don't have access to staging to view.).

**Comment by regineheberlein** [comment]
@cathyprinceton I'm afraid staging doesn't export to Alma. The archivists will review the records in ArchivesSpace before we run this in production.

**Comment by regineheberlein** [comment]
From Yang, via email from Cathy:
Archives 
Bibliography 
Biography 
Caricatures and cartoons 
Catalogs 
Congresses 
Correspondence 
Designs and plans 
Dictionaries 
Drama 
Drawings 
Early works to 1800 
Facsimiles 
Fiction 
Folklore 
In art 
Manuscripts Facsimiles 
Maps 
Miscellanea 
Newspapers 
Pamphlets 
Periodicals 
Photographs 
Pictorial works 
Posters 
Prayers and devotions 
Records and correspondence 
Slides 
Songs and music 
Sources 
Specimens 
Statistics 
Textbooks 
Texts 
Translations
