### ISSUE TITLE
Role in $e should not be capitalized

### ISSUE THREAD

**Issue by regineheberlein** [pulibrary/aspace_helpers#484]
### User Story -- briefly describe the problem:
Catalogers observe that there are large numbers of capitalized role designators.

We need to investigate where the capitalization is coming from.

### Example record(s) where you observed this problem
- MMSID: 
- Record (cut&paste): `Adam, Andy, ǂe Author` (?)

### What should that Record look like instead?
- Record: `Adam, Andy, ǂe author`
- Explanation (if applicable): 

### Impact
- How many records are affected by this issue?:
- OCLC error level:
  - [ ] Minor
  - [ ] Critical
  - [ ] Severe

### Anything else we may need to know to tackle this issue:
This issue was submitted by the Authorities DQ group in a meeting on 11/30 (also see https://docs.google.com/document/d/1-mcVnq9UCgBluq8ZqYgFmVcn2Z44EP9a/edit).

**Comment by cathyprinceton** [comment]
Examples: MMS ID 9921396633506421, 99125501033906421, 9930564673506421
(You can search Alma using Advanced search by Other system number (PULFA) and Relator (Creator))
Impact
    How many records are affected by this issue?: (Over 2400 records)
    OCLC error level:

Minor  [x] (more than minor, less than severe)
Critical
Severe

**Comment by regineheberlein** [comment]
Thank you @cathyprinceton !

**Comment by regineheberlein** [comment]
@cathyprinceton We addressed this at the application level; the values for the MARC relator list were loaded by our hosting vendor in all lower-case overnight. That should resolve the issue going forward.

FYI we're addressing the two local values in a separate ticket (#514).
