### ISSUE TITLE
Parse out dates, pre-/suffixes, titles, and fuller forms in personal names

### ISSUE THREAD

**Issue by regineheberlein** [pulibrary/aspace_helpers#485]
### User Story -- briefly describe the problem:
Catalogers observe that there are large numbers of names with dates in $a.

### Example record(s) where you observed this problem
- MMSID: 
- Record (cut&paste): `600 17  Clemons, Harry, 1879-1968. ǂ0 https://viaf.org/viaf/22503840 ǂ2 viaf (PULFA)C0627` [NB this is an obsolete example; the ind2, $0 and $2 are no longer there]

### What should that Record look like instead?
- Record: `600 10  Clemons, Harry, $d 1879-1968. ǂ1 https://viaf.org/viaf/22503840 ǂ1 https://viaf.org/viaf/22503840`
- Explanation (if applicable): 

### Impact
- How many records are affected by this issue?:
- OCLC error level:
  - [ ] Minor
  - [ ] Critical
  - [ ] Severe

### Anything else we may need to know to tackle this issue:
This issue was submitted by the Authorities DQ group in a meeting on 11/30 (also see https://docs.google.com/document/d/1-mcVnq9UCgBluq8ZqYgFmVcn2Z44EP9a/edit).

**Comment by regineheberlein** [comment]
Possible workflow:
1. get all person agents
2. filter by those having a date pattern in the title but not in the date fields
3. parse out beginning and end date
4. copy date string to date expression field
5. copy beginning and end date to date fields
6. post

**Comment by kevinreiss** [comment]
Archival Authorities Working Group is doing QA on this work. Deadline for that review is the end of April.

**Comment by kevinreiss** [comment]
Folks have completed the review work.

**Comment by regineheberlein** [comment]
blocked by #518
