### ISSUE TITLE
SOLR can't handle get requests with resolved ref's

### ISSUE THREAD

**Issue by regineheberlein** [pulibrary/aspace_helpers#509]
When sending get requests to the `resources`, `archival_objects`, `accessions`, `events`, and `digital_objects` endpoints with a resolve parameter to prefetch `linked_agents` and `subjects`, the request eventually hangs and times out.

The endpoints are paginated, with a default max page count of 250. We've experimented with dialing the page count down, and it succeeds in repo 3 with page count set to 60. In repo 4, it only succeeds when set all the way down to 30. At 30 in repo 3, it seems the loop hits a different ceiling of max API calls, and also fails.

Lyrasis is tentatively speculating that SOLR can't keep up with the requests.

**Comment by kevinreiss** [comment]
Lyrassis is looking into this as of 2/6.

**Comment by regineheberlein** [comment]
This has been shared with the ArchivesSpace developers and they are folding it into their ongoing work. I've supplied several more use cases where the API doesn't scale up sufficiently.
