### ISSUE TITLE
merge duplicate agent/person names based on new report

### ISSUE THREAD

**Issue by regineheberlein** [pulibrary/aspace_helpers#518]
### User story

The report produced by #471 revealed ~250 more duplicate agent records that need to be merged.

**Comment by regineheberlein** [comment]
Hi @amycvo and all, I have a handful of possible duplicates that need further looking into please. Please just merge/delete/otherwise resolve them as you look into them and let me know here which uri(s) should be kept!

- [ ] /agents/people/5335
/agents/people/11031
Both these records have the same name and viaf, but the bioghist for one says John and for the other Junius, indicating they are NOT the same person?

- [ ] /agents/people/5136
/agents/people/11064
Same name, same dates, different viaf ids?
 
- [ ] /agents/people/5225
/agents/people/11364
Are these the same person?

- [ ] /agents/people/27850
/agents/people/27851
Are these really two different people? Everything seems the same, but the birth year is off by 1 year

- [ ] /agents/people/14694
/agents/people/29149
Same person possibly? 

- [ ] /agents/people/13486
/agents/people/33361
Same person?

- [ ] /agents/people/8105
/agents/people/30148
Same name and dates, different viaf?

- [ ] /agents/people/6841
/agents/people/11798
birth year off by one year
 
- [ ] is /agent/people/11392
the same as /agents/people/8545 or /agents/people/14014 ?

- [ ] /agents/people/15313
/agents/people/15314
same people or different people?

- [ ] /agents/people/10393
/agents/people/8230
different death date

- [ ] /agents/people/18124
/agents/people/18125
different death date

- [ ] /agents/people/22914
/agents/people/22915
different death dates

**Comment by regineheberlein** [comment]
@amycvo and all: in addition to the above, the following need resolving please:

- [ ] /agents/people/11867 death date occurs before birth date: 1871-1843
- [ ] /agents/people/21142 death date occurs before birth date: 1898-1892
- [ ] /agents/people/24030 death date occurs before birth date: 1755-1642
- [ ] /agents/people/27030 If "della Francesca" is indeed this person's title, we need to move "Piero" to "primary name". Could you confirm?

**Comment by amycvo** [comment]
So far, I have updated and resolved the first four possible duplicates listed.

**Comment by regineheberlein** [comment]
@amycvo Thank you! Could you also indicate which of the uri's is the one that you kept please?

**Comment by amycvo** [comment]
Sure! I will edit this comment to add additional ones as I work through them: 

- both /agents/people/5335 and /agents/people/11031 were retained, because they are different people
- /agents/people/11064 was retained
- /agents/people/11364 was retained
- /agents/people/27850 was retained
- /agents/people/29149 was retained 
- /agents/people/33361 was retained
- /agents/people/30148 was retained

**Comment by amycvo** [comment]
> @amycvo and all: in addition to the above, the following need resolving please:
> 
> * [x]  /agents/people/11867 death date occurs before birth date: 1871-1843
> * [x]  /agents/people/21142 death date occurs before birth date: 1898-1892
> * [x]  /agents/people/24030 death date occurs before birth date: 1755-1642
> * [x]  /agents/people/27030 If "della Francesca" is indeed this person's title, we need to move "Piero" to "primary name". Could you confirm?

Hi @regineheberlein , I have checked these as well. I saw the spreadsheet says DO NOT EDIT, so I indicate if and where I edited the info:  
- record updated in Aspace -- /agents/people/11867 death date was a typo, and should be 1943
- record updated in Aspace -- /agents/people/21142 death date was a typo, and should be 1848
- record updated in Aspace -- /agents/people/24030 death date was a typo, and should be 1573
- record NOT updated in Aspace -- /agents/people/27030: confirmed that "della Francesca" is indeed this person's title. Confirmed that we need to move "Piero" to "primary name"

**Comment by regineheberlein** [comment]
>  /agents/people/21142 death date occurs before birth date: 1898-1892
> record updated in Aspace -- /agents/people/21142 death date was a typo, and should be 1848

This is still not quite right? I'm skipping this one, please update it manually.

**Comment by amycvo** [comment]
> * /agents/people/21142

Hi @regineheberlein! In Aspace, I see the dates of existence being 1848-1892, is it still listed as 1898-1892 somewhere?

**Comment by regineheberlein** [comment]
I think the above note had a typo but the actual record was good! All's well!

**Comment by amycvo** [comment]
> * e was a typo, and should be 1848

Oh I see, I mixed up saying birth date with death date! Gotcha! Thanks for wrapping this project up for us :)
