### ISSUE TITLE
Investigate Git LFS usage

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/aspace_helpers#525]
It appears Github thinks we are still using its LFS - see https://github.com/organizations/pulibrary/settings/billing/summary
![image](https://github.com/pulibrary/aspace_helpers/assets/45948126/dc2e17b8-030b-4f57-80c7-2bb6e144c10f)

At one point we investigated using LFS as an alternative for keeping EAD snapshots (around Spring 2022), but ultimately decided against it. 

We should determine why Github billing still thinks we are storing LFS with them, and find a way to delete it, so we are not accidentally billed in future.

### What we've tried
```zsh
git lfs ls-files
# no return
➜  aspace_helpers git:(main) git lfs migrate info
migrate: Fetching remote refs: ..., done.
migrate: Sorting commits: ..., done.
migrate: Examining commits: 100% (0/0), done.
```

### Implementation notes
See https://docs.github.com/en/repositories/working-with-files/managing-large-files/removing-files-from-git-large-file-storage#git-lfs-objects-in-your-repository  - do we really have to delete the whole repo to not be charged for storage?

**Comment by regineheberlein** [comment]
I've contacted Github about this

**Comment by maxkadel** [comment]
@rlskoeser has had a good experience with contacting GitHub support for this in the past.

**Comment by regineheberlein** [comment]
The LFS objects are gone. They still recommend following the steps described [here](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository) to remove them from the history. I'll look into that next week.
