### ISSUE TITLE
Adjust timing of aspace2alma processes so we don't miss the Analytics report

### ISSUE THREAD

**Issue by regineheberlein** [pulibrary/aspace_helpers#539]
### What maintenance needs to be done?
https://github.com/pulibrary/aspace_helpers/issues/538 suggests that on some days, Analytics runs before the latest data snapshot becomes available to it. 

Push the Analytics report (`sc_active_barcodes`) back by one hour and re-schedule the dependent aspace2alma processes accordingly.

### Level of urgency
- [x] High
- [ ] Moderate
- [ ] Low

### Why is this maintenance needed?
- So the Analytics report doesn't report out old data.

### Acceptance criteria
 - [ ] `sc_active_barcodes.csv` is current as of 8pm the previous day

**Comment by mzelesky** [comment]
Just let me know when you're ready for the schedule of the Analytics report to be updated. I would plan on shifting  the schedule to 3 AM instead of 1 AM.

**Comment by regineheberlein** [comment]
Thanks @Mark C. ***@***.***>. I’ll let you know by the end of the week.

Regine Heberlein (she/her)
Library IT Data Analyst
609-258-6156
***@***.******@***.***>

**My working day may not be your working day. Please do not feel obliged to reply to this email outside of your regular working hours.**



From: mzelesky ***@***.***>
Date: Wednesday, April 24, 2024 at 1:02 PM
To: pulibrary/aspace_helpers ***@***.***>
Cc: Regine I. Heberlein ***@***.***>, Author ***@***.***>
Subject: Re: [pulibrary/aspace_helpers] Adjust timing of aspace2alma processes so we don't miss the Analytics report (Issue #539)

Just let me know when you're ready for the schedule of the Analytics report to be updated. I would plan on shifting the schedule to 3 AM instead of 1 AM.

**Comment by regineheberlein** [comment]
Considerations and current state
- Alma runs on Eastern time and falls back/springs forward with Daylight Savings
- ASpace runs on UTC
- lib-sftp runs on UTC

**Comment by regineheberlein** [comment]
If we push the Analytics report back by 2 hrs, i.e. to run at 3am Eastern, it will finish at 7:30 UTC (summer) / 8:30 UTC (winter). aspace2alma runs at 8:30 UTC, so we have a conflict in winter.

So we need to push aspace2alma back correspondingly. It would run at 10:30 UTC and finish at 1pm UTC (summer) / 2pm UTC (winter). The Alma import job runs at 1pm UTC (summer) / 2pm UTC (winter), so we have a conflict year-round. 

So we also need to push the Alma import job back correspondingly, which would mean it only runs mid-morning at 11am Eastern.

**Comment by mzelesky** [comment]
Do you have concerns about the job running during the workday? It doesn't seem like a problem to me, but I might not understand staff considerations.

**Comment by mzelesky** [comment]
Timings were adjusted as of 9:10 AM on 4/29.

**Comment by regineheberlein** [comment]
The corresponding aspace2alma schedule change is now also in place. Thanks again!
