### ISSUE TITLE
The as_marcao plugin can't connect to lib-sftp

### ISSUE THREAD

**Issue by regineheberlein** [pulibrary/aspace_helpers#540]
The marc_ao plugin sends component/archival_object records for select collections to Alma via lib-sftp. It last succeeded on March 8.

This code is an [ArchivesSpace plugin](https://github.com/hudmol/as_marcao/tree/7535c4e42b88d81b3788c20a7228d3f8e7fa65a5) that connects to our sftp server from Lyrasis.

```
Statussftp_fail
Errornet.schmizz.sshj.userauth.UserAuthException: Exhausted available authentication methods
Last Success At2024-03-08 22:22:00 -0500
Started At2024-04-22 22:22:00 -0400
Completed At2024-04-22 22:29:14 -0400
```

Configuration:
```
Schedule22 22 * * *
Resource Selectorboolean_1
SFTP Hostlib-sftp-prod1.princeton.edu
SFTP Userlib-aspacesftp@pu.win.princeton.edu
SFTP Password********
SFTP Path/alma/aspace/
```

This corresponds to the last file saved to lib-sftp on March 9 (server time):
`Mar  9 03:22 marcao_export.xml`

**Comment by regineheberlein** [comment]
possible things to pursue, as far as @maxkadel and I have been able to look into this:
- did a firewall rules change occur on March 8 that might have locked Lyrasis out?
- is the oauth version used by the plugin too old? `You have installed oauth2 version 1.4.11, which is EOL.`
- is the way the [sftp class used by the plugin](https://github.com/hudmol/as_marcao/blob/7535c4e42b88d81b3788c20a7228d3f8e7fa65a5/backend/lib/sftp_uploader.rb) still right, or has something changed that would disallow this way to ssh?

**Comment by regineheberlein** [comment]
Lyrasis confirms we have the correct IP address and `nc` succeeds.

We need to change the directory owner to `lib-aspacesftp` and check that the password hasn't changed.

**Comment by kayiwa** [comment]
I am able to successfully connect when I remove the `pu.win.princeton.edu` successfully

**Comment by regineheberlein** [comment]
FYI Blake didn't get to it over the weekend but is going to put that in tonight.

**Comment by regineheberlein** [comment]
Ok, that's in place, here's to hoping for tonight's run!

```
Configuration
Schedule 22 22 * * *
Resource Selector boolean_1
SFTP Host lib-sftp-prod1.princeton.edu
SFTP User lib-aspacesftp
SFTP Password ********
SFTP Path /alma/aspace/
```

**Comment by regineheberlein** [comment]
@kayiwa : the ssh failed again, with the new sftp username in place:

```
Last Export
Status sftp_fail
Error net.schmizz.sshj.sftp.SFTPException: Permission denied
Last Success At 2024-03-08 22:22:00 -0500
Started At 2024-04-29 22:22:00 -0400
Completed At 2024-04-29 22:28:15 -0400
Resource IDs 2168, 2214, 3950
AOs Exported 3970
Export File Path /archivesspace/data/shared/marcao/marcao_export.xml


Configuration
Schedule 22 22 * * *
Resource Selector boolean_1
SFTP Host lib-sftp-prod1.princeton.edu
SFTP User lib-aspacesftp
SFTP Password ********
SFTP Path /alma/aspace/
```

**Comment by regineheberlein** [comment]
I'm noticing that the directory is owned by `lib-aspacesftp` on staging but `almasftp` on prod. Could it be as simple as setting it to `lib-aspacesftp` on prod?

**Comment by regineheberlein** [comment]
Update: @kayiwa updated the owner.

**Comment by regineheberlein** [comment]
This is now working again, thanks @kayiwa and @maxkadel !
