### ISSUE TITLE
get barcodes for AC297 top_container records from corresponding Alma item records

### ISSUE THREAD

**Issue by regineheberlein** [pulibrary/aspace_helpers#550]
### User story
We have a legacy data issue where Alma item records have barcodes for AC297 containers, but the corresponding ASpace top_container records don't know about it.

We want to get the barcodes from Alma and add them to the ASpace records.

### Source of the data to be imported or updated
Alma item records

### Implementation notes, if any
- [x] Export Alma item records as csv
- [x] Export ASpace top_container records as csv
- [x] Export ASpace components + containers from EAD (to have title as an additional match point)
- [x] Match on container type + item no. or unittitle
- [ ] Import barcodes to ASpace

**Comment by regineheberlein** [comment]
58 matches found. @LynnDurgin are you ok putting those in manually?

**Comment by kevinreiss** [comment]
Will ping lynn again.

**Comment by LynnDurgin** [comment]
Hi @kevinreiss and @reginehberlein, Yup, that is the plan. I just haven't had time to do it yet.
