### ISSUE TITLE
link from catalog to finding aid for C0140.1 is broken

### ISSUE THREAD

**Issue by regineheberlein** [pulibrary/aspace_helpers#554]
From Faith via Slack:

> I noticed that the link to the finding aids site for C0140.1 bib records is broken; see https://catalog.princeton.edu/catalog/99130781247006421. I'm assuming this has something to do with the fact that pulfalight uses underscores dashes rather than periods. Might there be a way to change the collection code portion of component IDs from C0140.1 to C0140_1 as part of the ao2marc process? Thanks for looking into this.

**Comment by regineheberlein** [comment]
Is `https://findingaids.princeton.edu/catalog/C0140.1_c22395-29044` but should be `https://findingaids.princeton.edu/catalog/C0140-1_c22395-29044`

**Comment by regineheberlein** [comment]
This record is generated by the [as_marcao plugin](https://github.com/hudmol/as_marcao):

It takes the value of the ref_id field: "C0140.1" and concatenates it with the domain ([line 396](https://github.com/hudmol/as_marcao/blob/main/backend/model/marc_ao_mapper.rb#L396)).

We could put in a PR with a regex that looks for any period occurring after the string "catalog" and is sandwiched between two digits. 

That would affect all finding aids that export components to Alma, so we'd want to make sure this wouldn't break the url for other records (including future ones?).

**Comment by regineheberlein** [comment]
@faithc @LexydeG ^

**Comment by regineheberlein** [comment]
It would, but that shouldn't dictate how we name collections. I just want to make sure we don't break anything else in the process of making this change!

**Comment by faithc** [comment]
Would it be worth trying to see if it works and if it does break anything we can then change the collection code? There are only 3 or 4 collections that get the ao2marc process, correct?  

It's not a huge deal obviously, but if we do end up changing the collection code, I'll have to update the finding aid, including creating another ARK, and the box and folder labels for the items that have already been added.

**Comment by faithc** [comment]
That logic makes sense to me, Regine. I don't think that change would affect anything else in the record?

**Comment by regineheberlein** [comment]
@faithc "Try and see" in this case involves a vendor and (possibly) money changing hands, so I'd rather not take that approach.

Thanks for confirming! I'll get the ball rolling.

**Comment by faithc** [comment]
@regineheberlein Ah, ok, I didn't realize that. I can't definitely say it won't break anything. And if it involves all of that, perhaps we should just change the collection code. @LexydeG what say you?

**Comment by LexydeG** [comment]
@regineheberlein @faithc Closing the Slack discussion loop. @faithc , go ahead and update the identifier from C0140.1 to the next available collection number in all needed areas when you have a chance. Can you let me know what the new number is?

**Comment by regineheberlein** [comment]
Closing this ticket after some additional off-ticket discussion with Lexy. The approach will be to not touch the transformation code but use a naming convention for the collection code that avoids the dot. Thanks @LexydeG !
