### ISSUE TITLE
"Photographic Prints" genre term displays as "photographic_prints" in Blacklight

### ISSUE THREAD

**Issue by regineheberlein** [pulibrary/aspace_helpers#619]
**Describe the bug**
When archivists enter the genre term "Photographic Prints" in ArchivesSpace, it appears as "photographic_prints" in the catalog. 

**Steps to replicate**
https://catalog.princeton.edu/catalog/99131270506506421

**Expected behavior**
Should display as "Photographic Prints"

### Impact of this bug
This is at best confusing to users.

**Comment by regineheberlein** [comment]
Check where this happens:
- [ ] on export from ArchivesSpace via the MARC-XML endpoint
- [ ] on import to Alma via a normalization job
- [ ] in bibdata

**Comment by regineheberlein** [comment]
The record source is an archival object in ArchivesSpace, C1778_c79837-86259. The $300 in the MARC record comes out as `a| 1 f| photographic_prints`, which is in turn the data source for the `Description` label.

The MARC exporter apparently grabs the `value` from `https://aspace.princeton.edu/staff/enumerations?id=14` when it should grab the `translation`.

This can be addressed in the CVL in our ArchivesSpace instance.

**Comment by maxkadel** [comment]
Yay! Finished!
