### ISSUE TITLE
make a new xml transformation for digitization purposes

### ISSUE THREAD

**Issue by regineheberlein** [pulibrary/aspace_helpers#623]
Amy needs an additional transformation from EAD to CSV to support digitization workflows. The [existing one](svn://lib-svn.princeton.edu/libsvn/trunk/rbscXSL/Digitization tools/ead2csv.xquery) only pulls from leaf-level components, but we now need one that pulls from every level AND indicates the nesting depth.

**Comment by regineheberlein** [comment]
@amycvo 

One question: how would you like me to indicate the nesting depth of the components? I'm thinking a numerical scale starting at "0", meaning the component is at the highest possible level of the hierarchy (i.e. has 0 ancestors that are themselves components), does that make sense? So nesting depth "1" means 1 deep, i.e. 1 ancestor that is itself a component, depth "2" means 2 deep / 2 ancestors that are themselves components, etc.

I favor this approach because it aligns with how ASpace records depth, but if you prefer something different, please feel free to suggest it!

Example:

| cid | level | nesting depth | unittitle | unitdate | container |
| --- | ----- | ------------- | -------- | -------- | ---------- | 
aspace_MC147_c00001 | series | 0 | Series 1: Organizational Files | 1922-1995 | 
 aspace_MC147_c00002 | subseries | 1 | Subseries 1: Administration | 1923-1994 | 
 aspace_MC147_c00003 | file | 2 | Annual Meetings | 1925-1936, 1938-1958 | box 1 folder 1-32
 aspace_MC147_c00004 | file | 2 | Annual Meetings | 1959-1968 | box 2 folder 1-10
 aspace_MC147_c00005 | file | 2 | Annual Meetings | 1969-1989 | box 3 folder 1-20
 aspace_MC147_c00006 | file | 2 | Annual Meetings | 1990-1993 | box 4 folder 1-4

**Comment by amycvo** [comment]
Yes, I believe this approach of beginning a numerical scale at 0 makes the most sense!

**Comment by regineheberlein** [comment]
Thanks @amycvo !
