### ISSUE TITLE
aspace2alma is not picking up changes

### ISSUE THREAD

**Issue by regineheberlein** [pulibrary/aspace_helpers#638]
**Describe the bug**
Kyler is not seeing item records with new location from C0129 reflected in Alma.

**Steps to replicate**
Look at the item records for boxes 36, 37, 39-56. Their holding is mss.

**Expected behavior**
The same boxes should have holding scarcpxm

### Impact of this bug
When a patron requests the box, the system doesn't know that the box is at ReCAP.

**Comment by regineheberlein** [comment]
The ASpace account was inadvertently disabled. We re-enabled it and the process is running. However, it is still not picking up the changes to C0129.

**Comment by regineheberlein** [comment]
Running branch `reverted` the process exited last night after successfully authenticating without having processed any records. The log indicates it got `nil` for the resource uri's (l74). When running locally, the method succeeds.

**Comment by regineheberlein** [comment]
we think this is fixed by #639

**Comment by maxkadel** [comment]
from the log_err.txt from 12/16/2024

```
/opt/aspace_helpers/releases/20241216165129/helper_methods.rb:325:in `block in get_all_resource_uris_for_institution': undefined method `each' for nil:NilClass (NoMethodError)

    ids_by_endpoint.each do |id|
                   ^^^^^
	from /opt/aspace_helpers/releases/20241216165129/helper_methods.rb:318:in `each'
	from /opt/aspace_helpers/releases/20241216165129/helper_methods.rb:318:in `get_all_resource_uris_for_institution'
	from get_MARCxml.rb:75:in `fetch_and_process_records'
	from get_MARCxml.rb:321:in `<main>'
```

**Comment by regineheberlein** [comment]
Strangely, the method does return the uri's locally.

**Comment by maxkadel** [comment]
It looks like the user is successfully logging in, but then does not have permission to actually do things. 

```bash
ssh deploy@lib-jobs-prod2
cd /opt/aspace_helpers/current
bundle exec irb
```
```ruby
irb(main):005:0> require_relative './helper_methods.rb'
=> true
irb(main):006:0> aspace_login
# looks like it returns a happy ArchivesSpace::Client object
# @client looks like the same happy ArchivesSpace::Client object
irb(main):008:0> endpoint = 'repositories/3/resources'
=> "repositories/3/resources"
irb(main):009:0> @client.get(endpoint, { query: { all_ids: true } }).parsed
=> {"error"=>"Access denied"}
```

**Comment by regineheberlein** [comment]
Yup, turns out we needed to bump up the privileges for it to do more than just log in. Thanks @maxkadel !

**Comment by christinach** [comment]
done

**Comment by regineheberlein** [comment]
The user in ASpace wasn't set up with the right privileges. Fixed.
